"""empty message

Revision ID: 09dcc15df575
Revises: 60300d5b691f
Create Date: 2019-01-04 16:20:11.121879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dcc15df575'
down_revision = '60300d5b691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('celebrates', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'celebrates')
    # ### end Alembic commands ###
