"""empty message

Revision ID: 60300d5b691f
Revises: fb5a10a70083
Create Date: 2019-01-04 14:34:49.059529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60300d5b691f'
down_revision = 'fb5a10a70083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approved', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'approved')
    # ### end Alembic commands ###
