"""empty message

Revision ID: 995b48d1619f
Revises: f2d122c30674
Create Date: 2019-01-05 16:47:48.979252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995b48d1619f'
down_revision = 'f2d122c30674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chats', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chats')
    # ### end Alembic commands ###
