"""empty message

Revision ID: f2d122c30674
Revises: 86dbe6a707bf
Create Date: 2019-01-04 22:11:36.577661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d122c30674'
down_revision = '86dbe6a707bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'timestamp')
    op.drop_column('deposit', 'timestamp')
    # ### end Alembic commands ###
