"""empty message

Revision ID: fb5a10a70083
Revises: ec5b7c77ace0
Create Date: 2018-09-30 13:00:32.299059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5a10a70083'
down_revision = 'ec5b7c77ace0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('birthday_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment', 'birthday', ['birthday_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'birthday_id')
    # ### end Alembic commands ###
